license="MIT"
modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees/issues"

[[mods]]
modId="dynamictrees"
version="${file.jarVersion}"
displayName="Dynamic Trees"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/DynamicTrees.json?raw=true"
displayURL="http://minecraft.curseforge.com/projects/dynamictrees"
logoFile="logo.png"
credits="MaxHyper & Harley O'Connor for the 1.16 port\nNyfaria & SizableShrimp for the 1.18 and 1.19 port"
authors="Ferreusveritas"
description='''
Progressively growing trees.. forests that spread'''

[[dependencies.dynamictrees]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamictrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
