license="MIT"
modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/ferreusveritas/DynamicTrees/issues"

[[mods]]
modId="dynamictrees"
version="${file.jarVersion}"
displayName="Dynamic Trees"
#updateJSONURL="http://minecraft.curseforge.com/projects/dynamictrees"
displayURL="http://minecraft.curseforge.com/projects/dynamictrees"
logoFile="logo.png"
credits="MaxHyper/supermassimo for the 1.14.4 Port"
authors="Ferreusveritas"
description='''
Progressively growing trees.. forests that spread'''

[[dependencies.dynamictrees]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamictrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
