name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '21 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 14
        stale-issue-message: 'This issue has gone stale due to inactivity. Please comment again if it is still an issue.'
        stale-issue-label: 'no-issue-activity'
        exempt-issue-labels: 'enhancement,stale exempt'
        days-before-pr-stale: 180
        stale-pr-message: 'This pull request has gone stale due to inactivity. Please comment again if it is still an issue.'
        stale-pr-label: 'no-pr-activity'
        exempt-pr-labels: 'stale exempt'
