name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '21 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has gone stale due to it having no activity for 90 days. Is this still a problem?'
        stale-issue-label: 'no-issue-activity'
        exempt-issue-labels: 'enhancement,stale exempt'
        stale-pr-message: 'This issue PR has gone stale due to it having no activity for 90 days. Is this still required?'
        stale-pr-label: 'no-pr-activity'
        exempt-pr-labels: 'stale exempt'
        days-before-stale: 90
        days-before-close: 30
